"""initial evidence store

Revision ID: 0eb065ca855e
Revises: 
Create Date: 2026-08-13 02:15:19.442004
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Autogenerate emite postgresql.JSONB(astext_type=Text()) para as colunas
# JSONCol; sem estes imports a migração quebra em tempo de execução.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401
from sqlalchemy.dialects import postgresql

revision = '0eb065ca855e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('br_record',
    sa.Column('record_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_norm', sa.String(length=512), nullable=False),
    sa.Column('authors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('advisors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('knowledge_area', sa.Text(), nullable=True),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('harvested_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('br_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_br_record_doi'), ['doi'], unique=False)
        batch_op.create_index('ix_br_source_year', ['source', 'year'], unique=False)
        batch_op.create_index('ix_br_title_norm', ['title_norm'], unique=False)

    op.create_table('fulltext_doc',
    sa.Column('doc_id', sa.String(length=40), nullable=False),
    sa.Column('work_key', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('access_status', sa.String(length=32), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('parser', sa.String(length=32), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    with op.batch_alter_table('fulltext_doc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fulltext_doc_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_fulltext_doc_work_key'), ['work_key'], unique=False)

    op.create_table('harvest_state',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.BigInteger(), nullable=True),
    sa.Column('last_ok_at', sa.BigInteger(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('integrity',
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('nature', sa.String(length=64), nullable=True),
    sa.Column('notice_doi', sa.String(length=255), nullable=True),
    sa.Column('notice_date', sa.String(length=32), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('doi')
    )
    with op.batch_alter_table('integrity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_status'), ['status'], unique=False)

    op.create_table('job',
    sa.Column('job_id', sa.String(length=40), nullable=False),
    sa.Column('pack_id', sa.String(length=40), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_state'), ['state'], unique=False)

    op.create_table('pack',
    sa.Column('pack_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('limitations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('pack_id')
    )
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pack_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pack_status'), ['status'], unique=False)

    op.create_table('venue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issn_l', sa.String(length=16), nullable=True),
    sa.Column('issns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('sjr', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('qualis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('jql', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index('ix_venue_issn_l', ['issn_l'], unique=False)
        batch_op.create_index('ix_venue_name_norm', ['name_norm'], unique=False)

    op.create_table('work',
    sa.Column('work_key', sa.String(length=128), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('pmcid', sa.String(length=32), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('openalex_id', sa.String(length=32), nullable=True),
    sa.Column('s2_id', sa.String(length=64), nullable=True),
    sa.Column('scielo_pid', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_norm', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('venue_name', sa.Text(), nullable=True),
    sa.Column('issn_l', sa.String(length=16), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('is_open_access', sa.Boolean(), nullable=True),
    sa.Column('oa_status', sa.String(length=32), nullable=True),
    sa.Column('integrity_status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen_at', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('work_key')
    )
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_arxiv_id'), ['arxiv_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_issn_l'), ['issn_l'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_openalex_id'), ['openalex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_pmcid'), ['pmcid'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_s2_id'), ['s2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_scielo_pid'), ['scielo_pid'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_title_norm'), ['title_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_year'), ['year'], unique=False)

    op.create_table('fulltext_span',
    sa.Column('span_id', sa.String(length=40), nullable=False),
    sa.Column('doc_id', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['fulltext_doc.doc_id'], ),
    sa.PrimaryKeyConstraint('span_id')
    )
    with op.batch_alter_table('fulltext_span', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fulltext_span_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index('ix_span_doc_ordinal', ['doc_id', 'ordinal'], unique=False)

    op.create_table('pack_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.String(length=40), nullable=False),
    sa.Column('item_type', sa.String(length=24), nullable=False),
    sa.Column('ref_key', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['pack.pack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pack_item', schema=None) as batch_op:
        batch_op.create_index('ix_pack_item_lookup', ['pack_id', 'item_type', 'rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_pack_item_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pack_item_ref_key'), ['ref_key'], unique=False)

    op.create_table('work_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('record_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.BigInteger(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['work_key'], ['work.work_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_key', 'source', name='uq_work_source')
    )
    with op.batch_alter_table('work_source', schema=None) as batch_op:
        batch_op.create_index('ix_work_source_source', ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_source_work_key'), ['work_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_source_work_key'))
        batch_op.drop_index('ix_work_source_source')

    op.drop_table('work_source')
    with op.batch_alter_table('pack_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pack_item_ref_key'))
        batch_op.drop_index(batch_op.f('ix_pack_item_pack_id'))
        batch_op.drop_index('ix_pack_item_lookup')

    op.drop_table('pack_item')
    with op.batch_alter_table('fulltext_span', schema=None) as batch_op:
        batch_op.drop_index('ix_span_doc_ordinal')
        batch_op.drop_index(batch_op.f('ix_fulltext_span_doc_id'))

    op.drop_table('fulltext_span')
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_year'))
        batch_op.drop_index(batch_op.f('ix_work_title_norm'))
        batch_op.drop_index(batch_op.f('ix_work_scielo_pid'))
        batch_op.drop_index(batch_op.f('ix_work_s2_id'))
        batch_op.drop_index(batch_op.f('ix_work_pmid'))
        batch_op.drop_index(batch_op.f('ix_work_pmcid'))
        batch_op.drop_index(batch_op.f('ix_work_openalex_id'))
        batch_op.drop_index(batch_op.f('ix_work_issn_l'))
        batch_op.drop_index(batch_op.f('ix_work_doi'))
        batch_op.drop_index(batch_op.f('ix_work_arxiv_id'))

    op.drop_table('work')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index('ix_venue_name_norm')
        batch_op.drop_index('ix_venue_issn_l')

    op.drop_table('venue')
    with op.batch_alter_table('pack', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pack_status'))
        batch_op.drop_index(batch_op.f('ix_pack_created_at'))

    op.drop_table('pack')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_state'))
        batch_op.drop_index(batch_op.f('ix_job_pack_id'))

    op.drop_table('job')
    with op.batch_alter_table('integrity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_status'))

    op.drop_table('integrity')
    op.drop_table('harvest_state')
    with op.batch_alter_table('fulltext_doc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fulltext_doc_work_key'))
        batch_op.drop_index(batch_op.f('ix_fulltext_doc_sha256'))

    op.drop_table('fulltext_doc')
    with op.batch_alter_table('br_record', schema=None) as batch_op:
        batch_op.drop_index('ix_br_title_norm')
        batch_op.drop_index('ix_br_source_year')
        batch_op.drop_index(batch_op.f('ix_br_record_doi'))

    op.drop_table('br_record')
    # ### end Alembic commands ###
