"""widen work_key to 255

Revision ID: 7fd1dcdde962
Revises: d9531188125f
Create Date: 2026-08-13 21:01:36.608593
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Autogenerate emite postgresql.JSONB(astext_type=Text()) para as colunas
# JSONCol; sem estes imports a migração quebra em tempo de execução.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401


revision = '7fd1dcdde962'
down_revision = 'd9531188125f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.alter_column('work_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('work_source', schema=None) as batch_op:
        batch_op.alter_column('work_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_source', schema=None) as batch_op:
        batch_op.alter_column('work_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.alter_column('work_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
