"""fulltext span section title

Revision ID: d9531188125f
Revises: 0eb065ca855e
Create Date: 2026-08-13 11:44:12.159888
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
# Autogenerate emite postgresql.JSONB(astext_type=Text()) para as colunas
# JSONCol; sem estes imports a migração quebra em tempo de execução.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401


revision = 'd9531188125f'
down_revision = '0eb065ca855e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fulltext_span', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fulltext_span', schema=None) as batch_op:
        batch_op.drop_column('section_title')

    # ### end Alembic commands ###
